name: chatly
description: Smart, Private & Anonymous Chat App - Privacy-first messaging with AI-powered features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Core Services
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.9
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.8
  firebase_storage: ^11.5.6
  cloud_functions: ^4.5.12
  
  # State Management
  provider: ^6.1.1
  
  # UI & Design
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utilities
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  connectivity_plus: ^5.0.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  intl: ^0.18.1
  crypto: ^3.0.3
  
  # Payments & Subscriptions
  in_app_purchase: ^3.1.11
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Local Storage
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Image Handling
  image_picker: ^1.0.5
  
  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/illustrations/
    - assets/images/wallpapers/free/
    - assets/images/wallpapers/plus/
    - assets/images/wallpapers/pro/
    - assets/images/emojis/
    - assets/animations/
    - assets/fonts/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
